import { Toaster } from '@/components/ui/toaster'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import Image from 'next/image'
import Link from 'next/link'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/**Header with app name*/}
        <Link
          href="/start"
          className="text-3xl font-bold p-4 mb-4 flex items-center gap-2"
        >
          <Image
            src="/dhyanascape-logo.webp"
            alt="Dhyanascape"
            width={100}
            height={100}
            className="w-10 h-10 rounded-full"
          />
          <h1>Dhyanascape</h1>
        </Link>
        {children}
        <Toaster />
      </body>
    </html>
  )
}
